spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/documents
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
server:
  tomcat:
    max-swallow-size: 64MB

